import { Component, lazy, Suspense, useState } from 'react'
import type { ReactNode } from 'react'
import { Button } from '@/components/ui/button'
import { supportPoints, searchPoints, selectPoint, referenceNotice, distanceNotice } from './reference'
import { parseOrigin, orderPoints, distanceLabel, destinationLinks } from './location'
import type { Origin } from './location'
import { checklist, readChecklist, writeChecklist } from './checklist'
import './shelters.css'
const SupportMap = lazy(() => import('./SupportPointMap'))
class MapBoundary extends Component<{ children: ReactNode }, { failed: boolean }> {
  state = { failed: false }
  static getDerivedStateFromError() { return { failed: true } }
  render() { return this.state.failed ? <p role="alert">Mapa indisponível. Consulte a lista e as coordenadas nos detalhes.</p> : this.props.children }
}
export function SheltersPage() {
  const [query, setQuery] = useState(''), [type, setType] = useState('')
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [latitude, setLatitude] = useState(''), [longitude, setLongitude] = useState('')
  const [origin, setOrigin] = useState<Origin | null>(null), [error, setError] = useState(''), [byDistance, setByDistance] = useState(false)
  const [marks, setMarks] = useState<string[]>(() => { try { return readChecklist(window.localStorage) } catch { return [] } })
  const [storageFailed, setStorageFailed] = useState(false)
  const point = selectedId ? selectPoint(selectedId) : undefined
  const visible = orderPoints(searchPoints(query, type), origin, byDistance)
  const nearest = origin ? orderPoints(supportPoints, origin, true)[0].id : null
  function updateMarks(next: string[]) { setMarks(next); try { setStorageFailed(!writeChecklist(window.localStorage, next)) } catch { setStorageFailed(true) } }
  function editOrigin(value: string, field: 'latitude' | 'longitude') { if (field === 'latitude') setLatitude(value); else setLongitude(value); setOrigin(null); setByDistance(false); setError('') }
  function calculate() { const next = parseOrigin(latitude, longitude); setOrigin(next); setError(next ? '' : 'Informe latitude entre −90 e 90 e longitude entre −180 e 180. Os dois campos são necessários.'); if (next) setByDistance(true) }
  const links = point ? destinationLinks(point) : null
  return <div className="support-page min-w-0 space-y-5">
    <header><p className="text-xs font-semibold text-[#25d3b6]">OMNI-ECORESCUE / V3</p><h1 className="mt-1 text-2xl font-semibold">Evacuação e Abrigos</h1><p className="mt-2 text-sm text-[#b5d2e2]">Preparação familiar e pontos de apoio de referência. Esta página independe da NASA.</p></header>
    <section className="light-panel space-y-2 p-4" aria-label="Limitações do cadastro"><p className="text-sm font-semibold">{referenceNotice}</p><p className="text-sm">8 pontos do cadastro original do MVP. Não há dados de ocupação, confirmação de evacuação ou acionamento de serviços.</p></section>
    <section className="light-panel space-y-3 p-4" aria-labelledby="support-search"><h2 id="support-search" className="text-lg font-semibold">Consultar pontos de referência</h2><div className="grid min-w-0 gap-3 sm:grid-cols-2"><label className="text-sm">Buscar nome ou cidade<input className="mini-select mt-1 w-full" value={query} onChange={e => setQuery(e.target.value)} placeholder="Nome ou cidade" /></label><label className="text-sm">Tipo de ponto<select className="mini-select mt-1 w-full" value={type} onChange={e => setType(e.target.value)}><option value="">Todos os tipos</option>{[...new Set(supportPoints.map(p => p.type))].sort().map(t => <option key={t}>{t}</option>)}</select></label></div>
      <form onSubmit={e => { e.preventDefault(); calculate() }} className="space-y-3"><h3 className="text-base font-semibold">Origem opcional para calcular distância</h3><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Latitude de origem<input className="mini-select mt-1 w-full" inputMode="text" value={latitude} onChange={e => editOrigin(e.target.value, 'latitude')} placeholder="−90 a 90" aria-invalid={!!error} aria-describedby={error ? 'origin-error' : undefined} /></label><label className="text-sm">Longitude de origem<input className="mini-select mt-1 w-full" inputMode="text" value={longitude} onChange={e => editOrigin(e.target.value, 'longitude')} placeholder="−180 a 180" aria-invalid={!!error} aria-describedby={error ? 'origin-error' : undefined} /></label></div><div className="flex flex-wrap gap-2"><Button type="submit">Calcular distâncias</Button><Button type="button" variant="outline" onClick={() => { setLatitude(''); setLongitude(''); setOrigin(null); setError(''); setByDistance(false) }}>Limpar origem</Button></div>{error && <p id="origin-error" role="alert" className="text-sm text-red-800">{error}</p>}<p className="text-xs text-muted-foreground">Coordenadas de origem permanecem apenas nesta sessão da página.</p></form><p className="text-sm">{distanceNotice}</p>
      <label className="block text-sm">Ordenar pontos<select className="mini-select mt-1 w-full sm:max-w-xs" value={byDistance ? 'distance' : 'name'} onChange={e => setByDistance(e.target.value === 'distance')}><option value="name">Nome</option><option value="distance" disabled={!origin}>Distância em linha reta</option></select></label>
    </section>
    <div className="grid min-w-0 items-start gap-4 lg:grid-cols-[minmax(250px,0.8fr)_minmax(0,1.5fr)]"><section className="light-panel min-w-0 space-y-3 p-4" aria-labelledby="support-list"><h2 id="support-list" className="text-lg font-semibold">Pontos cadastrados</h2><p role="status" className="text-sm">{visible.length} de 8 referências no filtro</p>{visible.length === 0 && <p>Nenhum ponto neste filtro. Isso não significa ausência de apoio na região.</p>}<ul className="space-y-2">{visible.map(p => <li key={p.id}><button className={`w-full rounded-xl border p-3 text-left ${p.id === selectedId ? 'border-teal-700 bg-teal-50' : 'border-slate-200 bg-white'}`} aria-pressed={selectedId === p.id} onClick={() => setSelectedId(p.id)}><span className="block text-sm font-semibold">{p.name}</span><span className="block text-sm">{p.city} · {p.type}</span><span className="mt-1 block text-xs">{distanceLabel(origin, p)}</span>{p.id === nearest && <span className="block text-xs font-semibold text-teal-800">Mais próximo no cadastro</span>}</button></li>)}</ul></section>
      <div className="min-w-0 space-y-4"><section className="light-panel min-w-0 space-y-3 p-4" aria-labelledby="support-map"><h2 id="support-map" className="text-lg font-semibold">Mapa de referências</h2><p className="text-xs">O mapa mantém os oito pontos; os filtros restringem a lista. Marcadores não representam disponibilidade.</p><MapBoundary><Suspense fallback={<p role="status">Carregando mapa. A lista permanece acessível.</p>}><SupportMap selectedId={selectedId} onSelect={setSelectedId} /></Suspense></MapBoundary></section>
      <section className="light-panel min-w-0 space-y-3 p-4" aria-labelledby="support-detail"><h2 id="support-detail" className="text-lg font-semibold">Detalhes do ponto</h2>{!point ? <p className="text-sm">Selecione um ponto na lista ou no mapa.</p> : <><h3 className="text-base font-semibold">{point.name}</h3><p className="text-sm">{point.city} · {point.type}</p><p className="text-sm">Coordenadas aproximadas: {point.latitude}, {point.longitude}</p><p role="status" className="text-sm font-semibold">{distanceLabel(origin, point)}</p><p className="text-xs break-words">Origem: {point.sourceFile}</p><p className="text-sm">{distanceNotice}</p><div className="flex flex-wrap gap-2"><Button asChild variant="outline"><a href={links!.google} target="_blank" rel="noopener noreferrer">Ver no Google Maps</a></Button><Button asChild variant="outline"><a href={links!.waze} target="_blank" rel="noopener noreferrer">Ver no Waze</a></Button></div><p className="text-xs">Abre serviço externo com as coordenadas do ponto cadastrado. O serviço não comprova condições de acesso ou disponibilidade e não constitui orientação oficial de evacuação.</p>{!visible.some(p => p.id === point.id) && <p className="text-xs">Ponto selecionado fora do filtro atual da lista.</p>}</>}</section></div></div>
    <section className="light-panel space-y-3 p-4" aria-labelledby="family-checklist"><h2 id="family-checklist" className="text-lg font-semibold">Preparação familiar</h2><p className="text-sm">Conteúdo editorial adaptado dos 14 itens do MVP. Revise necessidades de acessibilidade, orientações oficiais e circunstâncias da família; as marcações não são uma avaliação local.</p><p role="status" className="text-base font-semibold">{marks.length} de 14 itens revisados</p><div className="grid gap-2 sm:grid-cols-2">{checklist.map(([id, label]) => <label key={id} className="flex min-h-11 cursor-pointer items-center gap-3 rounded-lg border border-slate-200 p-3 text-sm"><input className="size-5 shrink-0 accent-teal-700" type="checkbox" checked={marks.includes(id)} onChange={e => updateMarks(e.target.checked ? [...marks, id] : marks.filter(m => m !== id))} />{label}</label>)}</div><Button variant="outline" onClick={() => updateMarks([])}>Limpar marcações</Button><p className="text-xs">Somente as marcações são salvas neste navegador. Completar a lista não garante proteção ou preparação suficiente.</p>{storageFailed && <p role="status" className="text-sm text-amber-900">Não foi possível salvar neste navegador. As marcações continuam disponíveis enquanto a página estiver aberta.</p>}</section>
    <section className="light-panel space-y-3 p-4" aria-labelledby="emergency-contacts"><h2 id="emergency-contacts" className="text-lg font-semibold">Contatos oficiais de emergência — Brasil</h2><div className="grid gap-2 sm:grid-cols-2">{[['Defesa Civil', '199'], ['Corpo de Bombeiros', '193'], ['SAMU', '192'], ['Polícia Militar', '190']].map(([name, number]) => <a key={number} className="flex min-h-11 items-center justify-between gap-2 rounded-lg border border-slate-200 p-3 text-sm" href={`tel:${number}`}><span>{name}</span><strong>{number}</strong></a>)}</div><p className="text-xs">O link abre a opção de chamada do dispositivo; não confirma contato ou atendimento.</p><a className="inline-flex min-h-11 items-center text-sm underline" href="https://www.gov.br/anatel/pt-br/regulado/numeracao/codigos-nacionais/servicos-de-utilidade-publica-e-de-emergencia" target="_blank" rel="noopener noreferrer">Fonte oficial: Anatel — códigos de emergência</a></section>
    <section className="light-panel space-y-2 p-4"><h2 className="text-base font-semibold">Limites e conectividade</h2><p className="text-sm">A consulta abrange somente oito registros históricos. Confirme a existência, a finalidade atual e as condições do ponto com os canais oficiais locais antes de deslocamentos.</p><p className="text-sm">Cadastro, cálculos e checklist não consultam NASA ou o backend. O mapa e os links externos precisam de conexão; não há garantia de abertura ou recarga offline.</p></section>
  </div>
}
